### ISSUE TITLE
TS.3: Prototype compliance checking for KP

### ISSUE THREAD

**Issue by mmersmann** [TranslatorIIPrototypes/BLComplianceService#1]
This prototype API will check compliance with BioLink for the KPs. If a resource is not compliant, the API will return an informative message about the specific failure. This will be developed in collaboration with the KPs.

Related:
[TS.3a: Prototype compliance checking for KP - ROBOKOP outputs](https://github.com/TranslatorIIPrototypes/BLComplianceService/issues/2)

**Comment by kshefchek** [comment]
closed via https://github.com/TranslatorIIPrototypes/BLComplianceService/pull/6
